# Generated by Django 4.0.3 on 2022-03-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('document_name', models.CharField(max_length=30, verbose_name='Document Name')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('folder_name', models.CharField(max_length=30, verbose_name='Folder Name')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('topic_name', models.CharField(max_length=256, verbose_name='Topic Name')),
                ('short_description', models.CharField(max_length=512, verbose_name='Short Topic Description')),
                ('long_description', models.TextField(verbose_name='Long Topic Description')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_topics', to='api.document')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['folder_name'], name='folder_name_idx'),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_documents', to='api.folder'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['topic_name'], name='topic_name_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_name'], name='document_name_idx'),
        ),
    ]
